stimuli:
  _target_: openretina.data_io.maheswaranathan_2023.stimuli.load_all_stimuli
  _convert_: object
  base_data_path: ${data.data_dir}
  stim_type: "naturalscene"
  normalize_stimuli: true


responses:
  _target_: openretina.data_io.maheswaranathan_2023.responses.load_all_responses
  _convert_: object
  base_data_path: ${data.data_dir}
  stim_type: "naturalscene"
  response_type: "firing_rate_20ms"
  fr_normalization: 1.0
