weight_visualization:
  _target_: openretina.callbacks.weight_visualization_callback.WeightVisualizationCallback
  every_n_epochs: 1
  start_epoch: 0
  call_on_train_epoch_end: true
  call_on_validation_epoch_end: false
  folder_path: "${paths.output_dir}/weight_plots/"  # set to null to skip weight visualization entirely
