_target_: openretina.data_io.base_dataloader.multiple_movies_dataloaders
_convert_: object # Keep python objects their class and does not convert to DictConfig
batch_size: 32
train_chunk_size: 1
clip_length: 1
num_val_clips: 640
allow_over_boundaries: true
