# Config file for loading natural movie data from the Sridhar et al. (2025) dataset
# Data originally from: https://gin.g-node.org/gollischlab/Sridhar_Gollisch_2025_Marmoset_RGC_Responses_Naturalistic_Movies
# Paper: https://www.biorxiv.org/content/10.1101/2024.03.05.583449v2

_target_: openretina.data_io.sridhar_2025.dataloaders.frame_movie_loader
_convert_: object
basepath: "${paths.data_dir}"
files:
  "01": "responses/cell_responses_01_fixation_movie.pkl"
  "02": "responses/cell_responses_02_fixation_movie.pkl"
  "03": "responses/cell_responses_03_fixation_movie.pkl"
  "04": "responses/cell_responses_04_fixation_movie.pkl"

fixation_files:
  "01": "fixations/complete_fixations_seed_2022and2023_s4_fixed.txt"
  "02": "fixations/complete_fixations_seed2022_s4.txt"
  "03": "fixations/complete_fixations_seed_2022and2023_s4_fixed.txt"
  "04": "fixations/complete_fixations_seed_2022and2023_s4_fixed.txt"
big_crops:
  "01": [35, 35, 55, 55]
  "02": [35, 35, 55, 55]
  "03": [35, 35, 55, 55]
  "04": [35, 35, 55, 55]
frame_file: "_img_"
img_dir_name: "stimuli_padded_4"
full_img_h: 300
full_img_w: 350
img_h: 150
img_w: 200
final_training: False
padding: 50
batch_size: 16
seed: null
train_frac: 0.8
subsample: 1
crop: 0
cell_index: null
num_of_trials_to_use: null
start_using_trial: 0
num_of_frames: ${model.core.temporal_kernel_sizes}
temporal_dilation: 1
hidden_temporal_dilation: 1
retina_index: null
device: 'cuda'
time_chunk_size: 100
num_of_layers: 2
excluded_cells:
    "01": [ 1, 5, 6, 7, 9, 10, 14, 16, 19, 20, 22, 25, 26, 29, 30, 31, 32, 33, 34, 35, 43, 46, 53, 54, 57, 62, 63, 64, 70, 71, 72, 77, 78, 79, 81, 82, 83, 86, 89, 90, 91, 94, 96, 97, 101, 103, 106, 112, 114, 116, 121, 122, 126, 127, 128, 130, 133, 136, 140, 143, 144, 145, 146, 148, 149, 155, 159, 162, 171, 176, 177, 178, 182, 185, 189, 191, 193, 197, 200, 209, 221, 222, 227, 230, 231, 234, 235, 236, 242, 243, 245, 247, 250, 254, 257, 258, 261, 262, 269, 271, 273, 274, 277, 281, 292, 296, 301, 303, 304, 307, 310, 311, 312, 313, 317, 318, 320, 325, 330, 331, 332, 333, 340, 341, 342, 344, 350, 352, 353, 354, 357, 358, 362, 363, 365 ]
    "02": [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 15, 16, 17, 18, 21, 24, 25, 26, 28, 29, 32, 42, 43, 44, 45, 46, 48, 50, 51, 53, 57, 58, 59, 60, 61, 64, 66, 69, 70, 72, 74, 77, 78, 80, 81, 82, 83, 84, 85, 86, 87, 89, 90, 91, 92, 95, 96, 98, 100, 101, 103, 107, 108, 111, 112, 113, 115, 117, 118, 119, 120, 121, 123, 124, 125, 127, 128, 129, 130, 131, 134, 136, 138, 140, 141, 143, 144, 145, 146, 147, 149, 150, 151, 152, 153, 154, 156, 159, 160, 162, 163, 164, 166, 170, 172, 173, 174, 175, 176, 179, 181 ]
    "03": []
    "04": [0, 1, 13, 15, 19, 21, 22, 24, 29, 33, 34, 40, 41, 46, 47, 49, 51, 55, 57, 59, 62, 65, 71, 84, 89, 90, 94, 99, 103, 108 ]

retina_specific_crops: True
hard_coded: null
flip_imgs: False
shuffle: null
get_locations: True
sta_dir: "stas"
