# Config file for loading natural movie data from the Sridhar et al. (2025) dataset
# Data originally from: https://gin.g-node.org/gollischlab/Sridhar_Gollisch_2025_Marmoset_RGC_Responses_Naturalistic_Movies
# Paper: https://www.biorxiv.org/content/10.1101/2024.03.05.583449v2

_target_: openretina.data_io.sridhar_2025.dataloaders.frame_movie_loader
_convert_: object
basepath: '/projects/extern/nhr/nhr_ni/nim00010/dir.project/marmoset_data/'
files:
  '01': 'responses/cell_responses_01_fixation_movie.pkl'
  '02': 'responses/cell_responses_02_fixation_movie.pkl'
  '03': 'responses/cell_responses_03_fixation_movie.pkl'
  '04': 'responses/cell_responses_04_fixation_movie.pkl'

fixation_files:
  '01': 'fixations/complete_fixations_seed_2022and2023_s4_fixed.txt'
  '02': 'fixations/complete_fixations_seed2022_s4.txt'
  '03': 'fixations/complete_fixations_seed_2022and2023_s4_fixed.txt'
  '04': 'fixations/complete_fixations_seed_2022and2023_s4_fixed.txt'
big_crops:
  '01': [35, 35, 55, 55]
  '02': [35, 35, 55, 55]
  '03': [35, 35, 55, 55]
  '04': [35, 35, 55, 55]
frame_file: "_img_"
img_dir_name: "stimuli_padded_4"
full_img_h: 300
full_img_w: 350
img_h: 150
img_w: 200
final_training: False
padding: 50
batch_size: 16
seed: null
train_frac: 0.8
subsample: 1
crop: 0
cell_index: null
num_of_trials_to_use: null
start_using_trial: 0
num_of_frames: 30
num_of_hidden_frames: 5
temporal_dilation: 1
hidden_temporal_dilation: 1
retina_index: null
device: 'cuda'
time_chunk_size: 100
num_of_layers: 1
excluded_cells:
  '01': []
  '02': []
  '03': []
  '04': []
retina_specific_crops: True
hard_coded: null
flip_imgs: False
shuffle: null
get_locations: True
sta_dir: 'stas'
