# core + data
hidden_channels: [16, 16]
in_shape: ??? # Required for core init. Needs to be assigned in the top level config.
n_neurons_dict: ???  # Set dynamically (e.g., in training script after loading sessions)

core:
  _target_: openretina.modules.core.base_core.SimpleCoreWrapper
  _convert_: object
  temporal_kernel_sizes: [21, 11]
  spatial_kernel_sizes: [11, 5]
  gamma_input: 0.0
  gamma_in_sparse: 0.0
  gamma_hidden: 0.0
  gamma_temporal: 40.0
  input_padding: 0
  hidden_padding: [0, 2, 2]
  maxpool_every_n_layers: null
  downsample_input_kernel_size: null
  convolution_type: "custom_separable"
  cut_first_n_frames: 0
  dropout_rate: 0.0
  channels: ???  # set dynamically based on input channels

readout:
  _target_: openretina.modules.readout.multi_readout.MultiKlindtReadoutWrapper
  _convert_: object
  in_shape: ???
  mask_l1_reg: 0.0
  weights_l1_reg: 0.0
  readout_bias: true
  weights_constraint: null
  mask_constraint: null
  init_mask: null
  init_weights: null
  init_scales: [[0.0, 0.15], [0.0, 0.15]]

# training
learning_rate: 0.01
