in_shape: ??? # # Required for kernels init. Needs to be assigned in the top level config.
n_neurons_dict: ??? # Required for init. Set dynamically in scripts/train.py based on loaded sessions.

core:
  _target_: openretina.modules.core.base_core.DummyCore
  _convert_: object
  cut_first_n_frames: 30

readout:
  _target_: openretina.modules.readout.multi_readout.MultipleLNPReadout
  _convert_: object
  in_shape: ???
  nonlinearity: "softplus"
  smooth_weight: 1.0
  sparse_weight: 1.0
  bias: True

# training
learning_rate: 0.005
optimizer: ${optimizer} # References the optimizer from defaults
lr_scheduler: ${lr_scheduler} # References the scheduler from defaults
