in_shape: ??? # # Required for kernels init. Needs to be assigned in the top level config.
n_neurons_dict: ??? # Required for init. Set dynamically in scripts/train.py based on loaded sessions.

core:
  _target_: openretina.modules.core.base_core.DummyCore
  _convert_: object

readout:
  _target_: openretina.modules.readout.multi_readout.MultipleSingleCellSeparatedLNPReadout
  _convert_: object
  in_shape: ???
  spat_kernel_size: [15, 15]
  rf_location: null  # Required for init. Set dynamically in scripts/train.py based on loaded sessions.
  nonlinearity: "softplus"
  rank: 1
  smooth_weight_spat: 1.0
  smooth_weight_temp: 1.0
  sparse_weight: 1.0
  smooth_regularizer_spat: "LaplaceL2norm"
  smooth_regularizer_temp: "Laplace1d"
  laplace_padding: null
  fit_gaussian: false
  normalize_weights: false

# training
learning_rate: 0.005

