defaults:
  - data_io: sridhar_wn_2025
  - quality_checks: null
  - dataloader: sridhar_wn_2025_ln
  - model: single_cell_lnp
  - training_callbacks:
    - early_stopping
    - lr_monitor
    - model_checkpoint
  - logger:
    - wandb
    - csv
  - trainer: default_deterministic
  - hydra: default
  - _self_ # values in this config will overwrite the defaults

exp_name: vystrcilova_2024_wn_lnp
seed: 42
check_stimuli_responses_match: false

dataloader:
  batch_size: 16

model:
  in_shape: ???

paths:
  load_model_path: null  # e.g. hoefling_2024_base_low_res or path to a .ckpt model
  cache_dir: ${oc.env:OPENRETINA_CACHE_DIRECTORY} # Remote files are downloaded to this location
  data_dir: ${paths.cache_dir}/wn_marmoset_data/ # Folder where local files are read from.
  log_dir: "./logs/ln_wn" # Used as parent for output_dir. Will store train logs.
  output_dir: ${hydra:runtime.output_dir} # Modify subpaths in the "hydra/default.yaml" config
  dataset_path: "https://huggingface.co/datasets/open-retina/wn_marmoset_data"

matmul_precision:
  _target_: torch.set_float32_matmul_precision
  precision: highest

trainer:
  max_epochs: 100
  accumulate_grad_batches: 1
  gradient_clip_val: 1
